---
title: "Report Greedy approach"
output: html_document
params:
  filelocation: none
  goldstandard: none
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#yaml::yaml.load()
```

```{r}
filelocation<-params$filelocation
filelocation<-"/home/anne/Masterarbeit/Test_pipeline/results_seed/biogrid/edgerewire/"
goldstandard<-params$goldstandard
goldstandard<-"/home/anne/Masterarbeit/Test_pipeline/sample_data//"
#setwd(filelocation)
method<-"sum"
```
```{r, echo = F}
require(data.table)
require(ggplot2)
require(gridExtra)
require(viridis)
require(cowplot)
```
# FDR Threshold
Threshold has been determined selecting the p-value which includes at most 5% of the random networks for each network size. Random networks are created sampling 1000 networks for each n, p-values are determined using Fisher's method. Some values have been interpolated using a
```{r}
fdr <- data.frame(V1 = c(), V2 = c(), V3 = c())
for (d in dir(filelocation)) {
fdr_temp <- fread(file.path(filelocation, d, "teststats.txt"))
fdr_temp$V3 <- d
fdr <- rbind(fdr, fdr_temp)

}
fdr$V3 <-
sapply(fdr$V3, function(x)
gsub(".tsv", "", gsub("result_", "", x)))
ggplot(data = fdr, aes(x = V1, y = V2, color = V3)) + geom_line() + ggtitle("Score Thresholds for each network size") +
xlab("Network size") + ylab("FDR threshold")
```

```{r}
# jaccard distance
jaccard <- function(g, f1) {
sub1 <- f1[V1 == g, 2:4]
sub1 <- sub1[order(sub1$V2)]
su <- unique(c(sub1$V2, sub1$V4))
intersect_1 <- length(which(su %in% gold$gene))
#print(intersect_1)
union_1 <- length(unique(c(su, gold$gene)))
# print(union_1)
jaccard <- intersect_1 / union_1
return(list(jaccard, union_1, intersect_1, g))
}

d <- dir(filelocation)
gold.files <- grep("expression", dir(goldstandard), value = T)

overall_jaccard <- list()
network_jaccard <-
data.frame(
jaccard_dists = c(),
union = c(),
intersection = c(),
graph = c(),
filename = c()
)
j0<-list()

for (gf in dir(filelocation)) {
gold <-fread(paste0(goldstandard, "/", gsub("result", "expression_type", gf), ".tsv"))
gold <- gold[V2 == "differential"]
gold <- gold[, 1]
colnames(gold) <- c("gene")

d.file <- gsub("expression_type", "result", gf)
f1 <- fread(file.path(filelocation, d.file, "file.graph"))
f1[, .N, by = V1]

su <- unique(c(f1$V2, f1$V4))
intersect_1 <- length(which(su %in% gold$gene))
union_1 <- length(unique(c(su, gold$gene)))
index_j <- intersect_1 / union_1
overall_jaccard[[gf]] <- index_j

jaccard_dists <- sapply(unique(f1$V1), function(g) jaccard(g, f1))
jaccard_dists<-data.table(jaccard_dists =jaccard_dists[1,], union = jaccard_dists[2,], intersection=jaccard_dists[3,], graph=jaccard_dists[4,])
jaccard_dists$filename<-gf
network_jaccard<-rbind(network_jaccard, jaccard_dists)
}


network_jaccard$jaccard_dists <-as.numeric(network_jaccard$jaccard_dists)
network_jaccard$union <- as.numeric(network_jaccard$union)
network_jaccard$intersection <-as.numeric(network_jaccard$intersection)
g1 <-ggplot(network_jaccard, aes(y = jaccard_dists, x = filename)) + geom_boxplot() +
  ggtitle("Jaccard distances to 'gold standard' toydata genes") + ylab("Jaccard distance") +
  theme(axis.text.x = element_text(angle = 90))
g2 <-ggplot(network_jaccard, aes(y = union, x = filename)) + geom_boxplot() +
  ggtitle("Union gene set") + ylab("") + theme(axis.text.x = element_text(angle = 90))
g3 <-ggplot(network_jaccard, aes(y = intersection, x = filename)) + geom_boxplot() +
  ggtitle("Intersect gene set") + ylab("") + theme(axis.text.x = element_text(angle = 90))
grid.arrange(g1, g2, g3, ncol = 3)
#plot(g1)
```

```{r}
node_table<-data.frame(V1 = c(), V2 = c(), V3 = c(), V4 = c(), V5 = c(), V6 = c(), V7 = c(), V8 = c(), V9 = c(), V10 = c(), V11=c())
min_score<-data.frame(V1 = c(), V2 = c(), V3 = c(), V4 = c(), V5 = c(), V6 = c(), V7 = c(), V8 = c(), V9 = c(), V10 = c(), V11=c())
for (d in dir(filelocation)) {
pval <- fread(file.path(filelocation, d, "file.stat"))
nodes <- fread(file.path(filelocation, d, "file.nodes"))
gg<-nodes[, .N, by=V2]
myframe<-merge(pval, gg, by.x = "V1", by.y="V2")
#myframe<-merge(myframe, network_jaccard, by.x = "V1", by.y="graph")
myframe[,norm:=V3/N]
myframe<-myframe[order(norm)]
myframe$filename<-d
node_table<-rbind(node_table, myframe)
min_score<-rbind(min_score, myframe[1])
}
network_jaccard$graph<-unlist(network_jaccard$graph)
node_table<-merge(node_table, network_jaccard, by.x = c("V1", "filename"), by.y=c("graph", "filename"))
min_score<-merge(min_score, network_jaccard, by.x = c("V1", "filename"), by.y=c("graph", "filename"))
node_table[,norm:=V3/N]
min_score[,norm:=V3/N]

```
```{r}

node_table$jaccard_dists<-as.numeric(node_table$jaccard_dists)
min_score$jaccard_dists<-as.numeric(min_score$jaccard_dists)


box1<-ggplot(min_score, aes(y=jaccard_dists, x="Jaccard"))+geom_boxplot()
box2<-ggplot(node_table, aes(y=jaccard_dists, x=filename))+geom_boxplot() + theme(axis.text.x = element_text(angle = 90))
grid.arrange(box1,box2, ncol=2)
```
