---
title: "Report Greedy approach"
output: html_document
params:
  filelocation: none
goldstandard: none
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#yaml::yaml.load()
```

```{r}
filelocation<-params$filelocation
  filelocation<-"/home/anne/Masterarbeit/batch_test/result_true/biogrid/"
goldstandard<-params$goldstandard
  goldstandard<-"/home/anne/Masterarbeit/batch_test/sample_data/biogrid/"
direct<-"/home/anne/Masterarbeit/batch_test/sample_networks/biogrid/"
#setwd(filelocation)
method<-"sum"
```
```{r, echo = F}
require(data.table)
require(ggplot2)
require(gridExtra)
require(viridis)
require(cowplot)
require(stringi)
require(RColorBrewer)
```
#FDR Threshold
Threshold has been determined selecting the p-value which includes at most 5% of the random networks for each network size. Random networks are created sampling 1000 networks for each n, p-values are determined using Fisher's method. Some values have been interpolated using a
```{r}
fdr <- data.frame(V1 = c(), V2 = c(), V3 = c(), V4=c())
dd<-dir(filelocation)
#dd<-grep("2453", dd, value = T)
for(pdir in dd){
for (d in dir(file.path(filelocation,pdir))) {
if(file.exists(file.path(filelocation, pdir, d, "teststats.txt"))){
fdr_temp <- fread(file.path(filelocation, pdir, d, "teststats.txt"))
}
fdr_temp$V3 <- d
fdr_temp$V4<-pdir
fdr <- rbind(fdr, fdr_temp)
}
}

```

```{r}
annotation_table<-data.table(unique(fdr$V4))
annotation_table<-annotation_table[,tstrsplit(V1, "_")]
annotation_table$orig<-unique(fdr$V4)
colnames(annotation_table)<-c("Network", "Aggr_meth", "FDR", "Perc_perm", "Seed", "Perm_meth", "Sele_meth", "Perm_hi_de", "Deg_hi", "background", "break1", "break2", "orig")
annotation_table$Perm_meth<-gsub("degreeawarenodeswap", "degreeaware", annotation_table$Perm_meth)
fdr<-merge(fdr, annotation_table, by.x = "V4", by.y= "orig")
```

```{r}
fdr$V3 <-sapply(fdr$V3, function(x)
gsub(".tsv", "", gsub("result_", "", x)))
fdr$V4<-gsub("degreeawarenodeswap", "", fdr$V4)
fdr$V4<-gsub("biogrid_normDegSum", "", fdr$V4)
fdr2<-fdr
ggplot(data = fdr, aes(x = V1, y = V2, color = V3)) + geom_line() + ggtitle("Score Thresholds for each network size") + xlab("Network size") + ylab("FDR threshold")+facet_wrap(~V4, scales = "free")+theme(legend.position = "bottom")
```



```{r}
# jaccard distance
jaccard <- function(g, f1) {
sub1 <- f1[V1 == g, 2:4]
sub1 <- sub1[order(sub1$V2)]
su <- unique(c(sub1$V2, sub1$V4))
intersect_1 <- length(which(su %in% gold$gene))
#print(intersect_1)
union_1 <- length(unique(c(su, gold$gene)))
# print(union_1)
jaccard <- intersect_1 / union_1
return(list(jaccard, union_1, intersect_1, g))
}

d <- dir(filelocation)
gold.files <- grep("expression", dir(goldstandard), value = T)

overall_jaccard <- list()
network_jaccard <-
data.frame(
jaccard_dists = c(),
union = c(),
intersection = c(),
graph = c(),
filename = c(),
run = c()
)

complete_graphs<-data.frame()

for(pdir in dir(filelocation)){
for (gf in dir(file.path(filelocation,pdir))) {
  if(file.exists(paste0(goldstandard, "/", gsub("result", "expression_type", gf), ".tsv")))
gold <-fread(paste0(goldstandard, "/", gsub("result", "expression_type", gf), ".tsv"))
gold <- gold[V2 == "differential"]
gold <- gold[, 1]
colnames(gold) <- c("gene")

d.file <- gsub("expression_type", "result", gf)
if(!file.exists(file.path(filelocation, pdir, d.file, "file.graph"))){
  next
}
f1 <- fread(file.path(filelocation, pdir, d.file, "file.graph"))
f1[, .N, by = V1]

cp<-f1
f1$file<-gf
f1$run<-pdir
complete_graphs<-rbind(complete_graphs,f1)

su <- unique(c(f1$V2, f1$V4))
intersect_1 <- length(which(su %in% gold$gene))
union_1 <- length(unique(c(su, gold$gene)))
index_j <- intersect_1 / union_1
overall_jaccard[[gf]] <- index_j

jaccard_dists <- sapply(unique(f1$V1), function(g) jaccard(g, f1))
jaccard_dists<-data.table(jaccard_dists =jaccard_dists[1,], union = jaccard_dists[2,], intersection=jaccard_dists[3,], graph=jaccard_dists[4,])
jaccard_dists$filename<-gf
jaccard_dists$run<-pdir
network_jaccard<-rbind(network_jaccard, jaccard_dists)
}
}

network_jaccard$jaccard_dists <-as.numeric(network_jaccard$jaccard_dists)
network_jaccard$union <- as.numeric(network_jaccard$union)
network_jaccard$intersection <-as.numeric(network_jaccard$intersection)

network_jaccard<-merge(network_jaccard, annotation_table, by.x="run", by.y="orig")

g1 <-ggplot(network_jaccard, aes(y = jaccard_dists, x = filename)) + geom_boxplot() +
ggtitle("Jaccard distances to 'gold standard' toydata genes") + ylab("Jaccard distance") +
theme(axis.text.x = element_blank())+guides(fill=FALSE)
g2 <-ggplot(network_jaccard, aes(y = union, x = filename)) + geom_boxplot() +
ggtitle("Union gene set") + ylab("") + theme(axis.text.x = element_text(angle = 90))+guides(fill=FALSE)
g3 <-ggplot(network_jaccard, aes(y = intersection, x = filename)) + geom_boxplot() +
ggtitle("Intersect gene set") + ylab("") + theme(axis.text.x = element_blank())+guides(fill=FALSE)
#grid.arrange(g1, g2, g3, ncol = 3)
#plot(g1)
```
```{r, echo=FALSE}

extractLegend <- function(gg) {
grobs <- ggplot_gtable(ggplot_build(gg))
foo <- which(sapply(grobs$grobs, function(x) x$name) == "guide-box")
grobs$grobs[[foo]]
}

g1 <-ggplot(network_jaccard, aes(y = jaccard_dists, x = run)) + geom_boxplot() +
ggtitle("Jaccard distances to 'gold standard' toydata genes") + ylab("Jaccard distance") +theme(axis.text.x = element_blank(), axis.title.x = element_blank(), plot.margin=unit(c(0,0,0,0), unit="cm"))+guides(fill=F)

aa<-melt(annotation_table, id.vars = "orig")
aa$variable<-as.factor(aa$variable)
aa$group <- paste0(aa$variable, aa$value)
a <-sapply(colnames(annotation_table), function(x) length(unlist(unique(annotation_table[,x, with=F])))==1)
a<-names(which(!a))
a<-grep("orig", a, value = T, invert = T)

if(length(a)!=0){
annotation_table<-annotation_table[orig %in% network_jaccard[, .N, by="run"]$run]
palettes<-c("BuGn", "Reds", "OrRd", "PuBu", "PuRd", "PuBu","BuGn", "Reds", "OrRd", "PuBu")
blank_plot<-list()
tile<-list()
for(ai in 1:length(a)){
pal<-brewer.pal(7, palettes[ai])
pal<-pal[2:7]
ggg<-ggplot(annotation_table)+geom_tile(aes_string(x="orig", y="''", fill=a[ai]),position = "identity")+
  scale_color_manual(aesthetics = "fill",values = pal)+
  guides(fill=guide_legend(title=a[ai]))
leg<-extractLegend(ggg)
x<-which(colnames(annotation_table)==a[ai])
m<--1+(length(unique(unlist(annotation_table[,..x])))*0.2)
blank_plot[[ai]]<-plot_to_gtable(ggplot()+geom_blank()+annotation_custom(leg, ymin=m))
tile[[ai]]<-ggg+theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(),plot.margin=unit(c(0,0,0,0), unit="cm"),  axis.line = element_blank())+guides(fill=F)
}
#plot.margin=unit(c(0,0,0,0), unit="cm"),
legend<-do.call(plot_grid, c(blank_plot, nrow=1, align="none"))
plo<-do.call(plot_grid, c(tile, align="v", ncol=1))
#leg_fin<-plot_grid(plo, legend, align = "v", ncol = 1, rel_heights = c(1/4,1/8))

#network_jaccard<-network_jaccard[graph %in% node_table[N==899]$V1 & run %in% node_table[N==899]$run]

#awesome<-ggplot(aa[variable %in% a])+geom_tile(aes(x=factor(orig), y=factor(variable), fill=value))+theme(axis.text =element_blank(), axis.title = element_blank(), axis.ticks = element_blank(), axis.line = element_blank(), legend.position = "bottom")
plot_grid(g1,plo, legend, ncol = 1, align = "v", rel_heights = c(0.5,0.25,0.25))
}
if(length(a)==0){
  plot(g1+theme(axis.text = element_text(), axis.ticks.x = element_line()))
}
# awesomelist<-list()
# for(i in 1:length(a)){
# awesome2<-ggplot(aa[variable %in% a[i]])+geom_tile(aes(x=factor(orig), y=factor(variable), fill=value))+theme(axis.text =element_blank(), axis.title = element_blank(), axis.ticks = element_blank(), axis.line = element_blank(), legend.position = "left", legend.title = element_blank(), plot.margin = unit(c(-1,0,-1,0,0), "cm"), legend.key.width =unit(0.2, "cm"), legend.text = element_text(size = 8, angle = 90), legend.direction = "vertical") 
# awesomelist[[i]]<-awesome2
# }
#p<-plot_grid(awesomelist[[1]], awesomelist[[2]],awesomelist[[3]],awesomelist[[4]], align = "v", nrow=4)

```
```{r, echo=F}
node_table<-data.frame(V1 = c(), V2 = c(), V3 = c(), V4 = c(), V5 = c(), V6 = c(), V7 = c(), V8 = c(), V9 = c(), V10 = c(), V11=c(), V12=c())
min_score<-data.frame(V1 = c(), V2 = c(), V3 = c(), V4 = c(), V5 = c(), V6 = c(), V7 = c(), V8 = c(), V9 = c(), V10 = c(), V11=c(), V12=c())
for(pdir in dir(filelocation)){
for (d in dir(file.path(filelocation,pdir))) {
  if(!file.exists(file.path(filelocation, pdir, d, "file.stat"))){
    next
  }
pval <- fread(file.path(filelocation, pdir, d, "file.stat"))
nodes <- fread(file.path(filelocation,pdir,  d, "file.nodes"))
gg<-nodes[, .N, by=V2]
#med<-nodes[,norm:=median(V3), by=V2]
myframe<-merge(pval, gg, by.x = "V1", by.y="V2")
#myframe<-merge(myframe, med, by.x="V1", by.y = "V2" )
myframe[,norm:=V3/N]
myframe<-myframe[order(norm)]
myframe$filename<-d
myframe$run<-pdir
node_table<-rbind(node_table, myframe)
min_score<-rbind(min_score, myframe[1])
}
}
```
```{r, echo=F}
network_jaccard$graph<-unlist(network_jaccard$graph)
node_table<-merge(node_table, network_jaccard, by.x = c("V1", "filename", "run"), by.y=c("graph", "filename","run"))
min_score<-merge(min_score, network_jaccard, by.x = c("V1", "filename", "run"), by.y=c("graph", "filename","run"))


box1<-ggplot(min_score, aes(y=jaccard_dists, x="Jaccard"))+geom_boxplot()
box2<-ggplot(node_table, aes(y=jaccard_dists, x=filename))+geom_boxplot() + theme(axis.text.x = element_blank())
#grid.arrange(box1,box2, ncol=2)
```
```{r}

sample_graphs<-dir(direct)
sample_graphs<-grep(".nodes", sample_graphs, value = T)
complete_networks<-data.frame(node=c(), network_size=c(), node_value=c(), degree=c())
for(sample in sample_graphs){
sub<-fread(file.path(direct, sample))
complete_networks<-rbind(complete_networks, sub)
}


complete_graphs<-as.data.table(complete_graphs)
x<-unlist(stri_split(complete_graphs$file,fixed="_"))
x<-matrix(x, ncol = 4, byrow = T)
x<-as.data.frame(x)
colnames(x)<-c("res", "g1", "g2", "g3")
complete_graphs<-cbind(complete_graphs, x[, 2:4])
complete_graphs$g1<-as.numeric(as.character(complete_graphs$g1))
complete_graphs$g2<-as.numeric(as.character(complete_graphs$g2))
complete_graphs$g3<-as.numeric(as.character(complete_graphs$g3))
```
```{r}
d1<-c()
d2<-c()
d3<-c()
count<-complete_graphs[, .N, by=c("V1","file", "run", "g1", "g2", "g3")]
for(t in 1:(nrow(count))){
triple<-count[t,]
#print(triple)
s<-complete_graphs[V1==triple$V1 & file==triple$file& run==triple$run]
nod<-data.table(nodes=unique(c(s$V2, s$V4)))
d1<-c(d1,length(which(nod$nodes %in% unique(complete_networks[V2==triple$g1]$V1))))
d2<-c(d2,length(which(nod$nodes %in% unique(complete_networks[V2==triple$g2]$V1))))
d3<-c(d3,length(which(nod$nodes %in% unique(complete_networks[V2==triple$g3]$V1))))

}
d<-data.table(d1,d2,d3)
count<-cbind(count, d)
#count
```



```{r}
j<-node_table[,which.max(jaccard_dists),by=c("run", "filename")]
m<-node_table[, which.min(norm), by=c("run", "filename")]

n<-node_table[,which.max(N), by=c("run", "filename")]
jj<-node_table[,max(jaccard_dists), by=c("run", "filename")]
jjj<-jj[which(m$V1-j$V1==0)]
jjn<-jj[which(m$V1-n$V1<3)]

max_jax<-node_table[which(node_table$N  %in% node_table[,max(N), by=c("run", "filename")]$V1)]
#max_jax
```
```{r}
bo<-ggplot(max_jax, aes(y=jaccard_dists, x=run))+geom_violin()+ggtitle("Jaccard indices reached by the largest candidate solutions")+theme(axis.text.x = element_blank())
plot(bo)
```


```{r}
count$perc1<-count$d1/count$g1
count$perc2<-count$d2/count$g2
count$perc3<-count$d3/count$g3

c<-count[which(node_table$N  %in% node_table[,max(N), by=c("run", "filename")]$V1)]
c<-melt(c[,.(run, file, perc1, perc2, perc3)], id.vars = c("run", "file"))
ggplot(c)+geom_violin(aes(y=value, x=variable))+ggtitle("Overlap with individual foreground networks")+xlab("Graph")+ylab("Percentage of overlap")+facet_wrap(~run)
```
